mpi:
  - nompi
  - impi  # [win]
  - mpich  # [unix]
  - openmpi  # [unix]
# https://github.com/conda-forge/opencv-feedstock/issues/493
MACOSX_SDK_VERSION:  # [osx]
  - 15.5             # [osx]

fortran_compiler:   # [win]
    - ifx           # [win]

fortran_compiler_version:   # [win]
    - '2025.*'              # [win]
impi_devel:                 # [win]
  - 2021.17                 # [win]

# native aarch64 runners, see https://conda-forge.org/docs/reference/runners/
github_actions_labels:   # [linux and aarch64]
  - ubuntu-24.04-arm     # [linux and aarch64]
